- src/Abstracts/TestBedFixture.cs
> Addresssed issue #42

- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Xunit.Microsoft.DependencyInjection.ExampleTests.csproj
- src/Xunit.Microsoft.DependencyInjection.csproj
> Upgraded NuGet packages #45

- src/Abstracts/TestBed.cs
> TestBed class is now implementing ICollectionFixture #48

- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Xunit.Microsoft.DependencyInjection.ExampleTests.csproj
- src/Xunit.Microsoft.DependencyInjection.csproj
> Upgraded Microsoft NuGet package

- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Xunit.Microsoft.DependencyInjection.ExampleTests.csproj
- src/Xunit.Microsoft.DependencyInjection.csproj
> Upgraded Microsoft LTS packages #64

- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Xunit.Microsoft.DependencyInjection.ExampleTests.csproj
- src/Xunit.Microsoft.DependencyInjection.csproj
> Upgraded Microsoft packages to 3.1.18

- src/Abstracts/TestBedFixture.cs
This PR closes #88 and closes #87
> Exposed `IConfigurationBuilder` #88

- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Fixtures/TestFixture.cs
- src/Abstracts/TestBedFixture.cs
> Fixed bug #91

- azure-pipeline-PR.yml
- azure-pipelines.yml
- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Fixtures/TestFixture.cs
- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/GlobalUsings.cs
- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/IntegrationTests.cs
- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Services/Calculator.cs
- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Services/ICalculator.cs
- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Services/Options.cs
- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/UnitTests.cs
- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Xunit.Microsoft.DependencyInjection.ExampleTests.csproj
- src/.editorconfig
- src/Abstracts/TestBed.cs
- src/Abstracts/TestBedFixture.cs
- src/Attributes/TestOrderAttribute.cs
- src/GlobalUsings.cs
- src/Logging/NilLoggerProvider.cs
- src/Logging/NoOpDisposable.cs
- src/Logging/OutputLogger.cs
- src/Logging/OutputLoggerProvider.cs
- src/TestsOrder/TestPriorityOrderer.cs
- src/Xunit.Microsoft.DependencyInjection.csproj
> Made the necessary amendments in the code per issue #93

- README.md
- src/Abstracts/TestBedFixture.cs
- src/Xunit.Microsoft.DependencyInjection.csproj
- src/package.nuspec
*  Removed the obsolete configuration file getter method
* Updated copyright year in the nuget config file
*Wired up environment variables
This PR closes #95
> Updated copyright year and conducted a slight code clean up. Wired up environment variables too. #95

- azure-pipeline-PR.yml
- src/package.nuspec
> Fixed the release build issue #95

- azure-pipeline-PR.yml
- azure-pipelines.yml
- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Fixtures/TestFixture.cs
- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Xunit.Microsoft.DependencyInjection.ExampleTests.csproj
- src/Abstracts/TestBedFixture.cs
- src/TestAppSettings.cs
This PR closes #102, closes #103, and closes #105 after the merge.
> Improvements

- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Fixtures/TestFixture.cs
- src/Abstracts/TestBedFixture.cs
- src/Xunit.Microsoft.DependencyInjection.csproj
This PR closes #109 and closes #110
> Remove the obsolete attribute and add the readme file to the NuGet package

- azure-pipeline-PR.yml
- azure-pipelines.yml
- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Fixtures/TestFixture.cs
- src/Abstracts/TestBedFixture.cs
This PR closes #112 after the merge
> Remove GetConfigurationFiles() method

- azure-pipeline-PR.yml
- azure-pipelines.yml
This PR closes #128 after the merge.
> Upgraded the build pipelines' SDK to version 6.0.402

- README.md
- azure-pipeline-PR.yml
- azure-pipelines.yml
- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Xunit.Microsoft.DependencyInjection.ExampleTests.csproj
- src/Xunit.Microsoft.DependencyInjection.csproj
This PR closes #147 after merging with the `main` branch.
> Support both net 6.0 and net 7.0 within the same csproj file

- azure-pipelines.yml
> Fix the build pipeline to accommodate version 8.x sentiment #205

- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Xunit.Microsoft.DependencyInjection.ExampleTests.csproj
Removed the subject nuget package
> Update Xunit.Microsoft.DependencyInjection.ExampleTests.csproj #229

- src/Abstracts/TestBedFixture.cs
> 243 minor bug the generic must be removed from the async scope getter

- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Xunit.Microsoft.DependencyInjection.ExampleTests.csproj
- src/Xunit.Microsoft.DependencyInjection.csproj
> Upgraded the NuGet packages

- azure-pipeline-PR.yml
- azure-pipelines.yml
- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Xunit.Microsoft.DependencyInjection.ExampleTests.csproj
- src/Xunit.Microsoft.DependencyInjection.csproj
> 268 upgrade nuget packages

- azure-pipeline-PR.yml
- azure-pipelines.yml
- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Xunit.Microsoft.DependencyInjection.ExampleTests.csproj
- src/Xunit.Microsoft.DependencyInjection.csproj
#291 Upgraded the packages and updated the CI pipelines accordingly - This PR closes #291
> #291 Upgraded the packages and updated the CI pipelines accordingly

- README.md
- azure-pipeline-PR.yml
- azure-pipelines.yml
- examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Xunit.Microsoft.DependencyInjection.ExampleTests.csproj
- src/Xunit.Microsoft.DependencyInjection.csproj
> Add versioning hints to the readme
